baseurl: ''
#exclude: [src, CNAME, "2012", "2013"]
#markdown: kramdown
api: 'https://script.google.com/macros/s/AKfycbyUhpTZp0iDiFvi1ckLheEUklMa9AE-HAnaJJPv0VC6Pv1UpiLhehuRRralr1BmullG/exec'
#source: _source
future: true

# Analytics
#ga:
#  enabled: true
#  code: "UA-24614711-3"

# start date of OSMGeoWeek
#date: 2016-11-13
