baseurl: ''
#exclude: [src, CNAME, "2012", "2013"]
#markdown: kramdown
api: 'https://script.google.com/macros/s/AKfycbwzCkuVB4AONNCguNQalomUjHbDOxXAlk6CI0rA76KvwBWurfrQ-4c82WQhnYhONCdC/exec'

future: true

# Analytics
#ga:
#  enabled: true
#  code: "UA-24614711-3"

# start date of OSMGeoWeek
#date: 2016-11-13
