baseurl: ''
#exclude: [src, CNAME, "2012", "2013"]
#markdown: kramdown
api: 'https://script.google.com/macros/s/AKfycbxuURSIFyg0mRs0YJy0c384oLHbnPmCk_tX6n5d9PoFDTq3pwidAGKmc41nJuCvuOaL/exec'

future: true

# Analytics
#ga:
#  enabled: true
#  code: "UA-24614711-3"

# start date of OSMGeoWeek
#date: 2016-11-13
