baseurl: ''
#exclude: [src, CNAME, "2012", "2013"]
#markdown: kramdown
api: 'https://script.google.com/macros/s/AKfycbxRpcAGMg7OjfQAJNUXokYyfYkUo6-DTrvi556xKcUU26e9GcuUtHIuNr4wFDMP091j/exec'

future: true

# Analytics
#ga:
#  enabled: true
#  code: "UA-24614711-3"

# start date of OSMGeoWeek
#date: 2016-11-13
